### PR TITLE
Hotfix/exclude forks with open issues

### PR DESCRIPTION
**Pull request by ticotheps**
# Description
- Refactors introductory comments at the top of 'spoon.js' to be more explicit.
- Adds 2 more conditions to the conditional 'if' statement that filters out repos that are not forks.
- Please check out the YouTube video demonstration of the changes I've made [here](https://youtu.be/VhR5LBgVq1k). 

Fixes # (issue)
- Prevents users from running the 'spoon.js' script on forked repos that still have open issues (i.e. - unresolved pull requests) on them.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Tested using my personal GitHub account and 2 personal repositories
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ticotheps** [comment]
Imagine that these two repos are my only forked repos that I want to turn into personal repos:
Screen Shot 2020-02-02 at 2 40 48 AM

**Comment by ticotheps** [comment]
Also imagine that I have an open PR on the "computer-architecture-cs24" repo...
comp_arch_open_issues_count_1_BEFORE
two_forked_repos

**Comment by ticotheps** [comment]
one_conditional
two_conditional
three_conditional

**Comment by ticotheps** [comment]
condition_1_2
condition_3

**Comment by ticotheps** [comment]
https://www.youtube.com/watch?v=VhR5LBgVq1k&feature=youtu.be

**Comment by birdcar** [comment]
Hi @ticotheps! 👋 

Thanks for opening this / the very thorough bug report and description of the changes.

After reviewing this and thinking about the use case/workflow, I _do_ believe that this belongs in spoon, but I want it to be an optional behavior. To that end, I've opened #14 as the beginning of work to convert spoon into something usable as a CLI rather than editing a janky script so that it mostly works.

Feel free to check out the todos in that PR if you want to contribute! I'll be working on opening and tagging issues / adding them to the project board so that we have a good idea of the work that needs to be done.

Closing this PR for now since it's on a branch that we won't be updating until #14  is merged.

**Pull request closed without merging**
